Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,25 +1,31 @@
 #!/usr/bin/env bash
 
+INSTALL_DIR=".install"
+
+RED="\e[31m"
+GREEN="\e[32m"
+YELLOW="\e[33m"
+BLUE="\e[34m"
+NOCOLOR="\e[0m"
+
 # HELP #
 display_usage() {
     echo "\
 Usage:
   run [command]
 HELP
-  help              h         show list of commands
+  help              h       show list of commands
 DOCKER COMMAND
   build_container   build
   run_container     run
   build_and_run     bnr
   connect_container co
   stop_container    stop
-  remove_container  rm
   stop_and_remove   snr
 INSTALLING COMMAND
-  create-project    create    create Symfony project with Maker bundle
-  db-install        db        install Doctrine and Symfony Form
-  qa-install        qa        install Php linters \
-";
+  install <script>  i       install specific script from '$INSTALL_DIR' directory";
+
+  exit 0
 }
 
 ##############
@@ -60,47 +66,43 @@ stop_and_remove() {
 ### INSTALL ###
 ###############
 
-# CREATE #
-create_project() {
-    # create
-    symfony new __project
-    mv __project/* . && mv __project/.* . && rm -r __project
-    curl https://raw.githubusercontent.com/cylmat/symplay/refs/heads/main/public/.htaccess -o public/.htaccess
+install() {
+    if [[ -z "$@" ]]; then
+        echo "Empty installation option."
+        exit 1
+    fi
 
-    # make
-    composer req --dev maker
-    chmod a+w -R .
-    echo 'Test' | bin/console make:controller
-    echo 'Access test page on "http://localhost:8123/test"'
+    INSTALL_SCRIPTS=$(ls ${INSTALL_DIR} | tr "\n" " ")
+    INSTALL_SCRIPTS_SHOW=$(ls ${INSTALL_DIR})
+
+    for i in "$@"; do
+        case $i in
+            list|ls)
+                echo -e "\n*** List of available scripts in '${YELLOW}$INSTALL_DIR${NOCOLOR}' directory ***"
+                echo -e "${BLUE}$INSTALL_SCRIPTS_SHOW${NOCOLOR}"
+            ;;
+            *)
+                for script in ${INSTALL_SCRIPTS[@]}; do
+                    if [[ "$@" == "$script" ]]; then
+                        echo "Installing '$script'"
+                        sh -c "bash $INSTALL_DIR/$script"
+                        exit 0
+                    fi
+                done
+                echo "'$@' not found."
+                exit 1
+            ;;
+        esac
+    done
+    exit 0
 }
-
-# DATABASE #
-db_install() {
-    # doctrine
-    composer req doctrine --no-interaction
-    sed -i -e 's/DATABASE_URL="postgresql/# DATABASE_URL="postgresql/' .env
-    sed -i -e 's/# DATABASE_URL="sqlite/DATABASE_URL="sqlite/' .env
-
-    # form
-    composer require form validator twig-bundle security-csrf
-    echo 'Use "bin/console make:entity" or "bin/console make:crud"'
-}
-
-# QA #
-qa_install() {
-    mkdir -p tools
-    composer req --dev --working-dir=tools friendsofphp/php-cs-fixer phpmd/phpmd phpunit/phpunit phpstan/phpstan
-
-    echo "See: [https://phpqa.io] and [https://github.com/easy-coding-standard]
-    Suggested: [https://github.com/jakzal/toolbox] and [https://github.com/EdgedesignCZ/phpqa]"
-}
-
-if [[ -z "$@" ]]; then
-  display_usage
-fi
 
 for i in "$@"; do
     case $i in
+        # install
+        install|i)
+            install $2
+        ;;
         # docker
         build_container|build)
             build_container
@@ -125,20 +127,12 @@ for i in "$@"; do
             stop_container
             remove_container
         ;;
-        # install
-        create_project|create)
-            create_project
-        ;;
-        db_install|db)
-            db_install
-        ;;
-        qa_install|qa)
-            qa_install
-        ;;
-        help|h)
+        # help
+        help|h|--help)
             display_usage
         ;;
     esac
 done
 
+display_usage
 exit 0
